name: Run unit test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-tes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test
